arm64: dts: renesas: rzg2ul-smarc: Drop including RZ/G2UL SoM DTSI
Drop including RZ/G2UL SoM DTSI in carrier board DTSI as the top level
board DTS file r9a07g043u11-smarc.dts includes both of them. Upstream
commit 53072ba67e534ddd208697d3465004738f1d4d61 ("arm64: dts: renesas:
rzg2ul-smarc: Include SoM DTSI into board DTS") already did this change
but it was re-introduced in below commit (for v6.1-cip):

ce658d9231044 ("arm64: dts: renesas: rzg2ul-smarc: Enable SCI0")

This change is in preparation for adding the Renesas RZ/Five RISC-V SoC.
Without this patch when re-using the RZ/G2UL DTS/I for the SMARC RZ/Five
board we see below build issues:

  DTC     arch/riscv/boot/dts/renesas/r9a07g043f01-smarc.dtb
./scripts/dtc/include-prefixes/arm64/renesas/rzg2ul-smarc-som.dtsi:106.23-124.4:
ERROR (phandle_references): /soc/ethernet@11c30000/ethernet-phy@7: Reference to non-existent node or label "irqc"

  also defined at arch/riscv/boot/dts/renesas/rzfive-smarc-som.dtsi:20.23-23.4
  also defined at ./scripts/dtc/include-prefixes/arm64/renesas/rzg2ul-smarc-som.dtsi:106.23-124.4
ERROR: Input tree has errors, aborting (use -f to force output)
make[2]: *** [scripts/Makefile.lib:406: arch/riscv/boot/dts/renesas/r9a07g043f01-smarc.dtb] Error 2
make[1]: *** [scripts/Makefile.build:500: arch/riscv/boot/dts/renesas] Error

Signed-off-by: Lad Prabhakar <prabhakar.mahadev-lad.rj@bp.renesas.com>
Signed-off-by: Pavel Machek <pavel@denx.de>